export default [
  {
    label: 'Admins',
    options: [
      { value: 'julianmcgrath@example.com', label: 'Julian Mc Grath' },
      { value: 'charlesblack@example.com', label: 'Charles Black' },
      { value: 'wendydavidson@example.com', label: 'Wendy Davidson' },
      { value: 'leonardoliver@example.com', label: 'Leonard Oliver' },
      { value: 'abigailmetcalfe@example.com', label: 'Abigail Metcalfe' },
    ],
  },
  {
    label: 'Non-Admins',
    options: [
      { value: 'benjaminparsons@example.com', label: 'Benjamin Parsons' },
      { value: 'annebuckland@example.com', label: 'Anne Buckland' },
      { value: 'janewallace@example.com', label: 'Jane Wallace' },
      { value: 'kimberlywalker@example.com', label: 'Kimberly Walker' },
      { value: 'joanbaker@example.com', label: 'Joan Baker' },
      { value: 'ireneparsons@example.com', label: 'Irene Parsons' },
      { value: 'elizabethedmunds@example.com', label: 'Elizabeth Edmunds' },
      { value: 'ellakerr@example.com', label: 'Ella Kerr' },
      { value: 'leonardwilson@example.com', label: 'Leonard Wilson' },
      { value: 'jackjohnston@example.com', label: 'Jack Johnston' },
      { value: 'sonianolan@example.com', label: 'Sonia Nolan' },
      { value: 'lillianedmunds@example.com', label: 'Lillian Edmunds' },
      { value: 'annerobertson@example.com', label: 'Anne Robertson' },
      { value: 'wandabutler@example.com', label: 'Wanda Butler' },
      { value: 'ianhudson@example.com', label: 'Ian Hudson' },
      { value: 'soniasharp@example.com', label: 'Sonia Sharp' },
      { value: 'avathomson@example.com', label: 'Ava Thomson' },
      { value: 'sophieabraham@example.com', label: 'Sophie Abraham' },
      { value: 'ameliaparr@example.com', label: 'Amelia Parr' },
      { value: 'penelopenorth@example.com', label: 'Penelope North' },
      { value: 'deirdrewright@example.com', label: 'Deirdre Wright' },
      { value: 'josephyoung@example.com', label: 'Joseph Young' },
      { value: 'nataliekelly@example.com', label: 'Natalie Kelly' },
      { value: 'mariacornish@example.com', label: 'Maria Cornish' },
      { value: 'stephenrutherford@example.com', label: 'Stephen Rutherford' },
      { value: 'ameliaarnold@example.com', label: 'Amelia Arnold' },
      { value: 'neilmitchell@example.com', label: 'Neil Mitchell' },
      { value: 'carlnewman@example.com', label: 'Carl Newman' },
      { value: 'cameronwilkins@example.com', label: 'Cameron Wilkins' },
      { value: 'faithturner@example.com', label: 'Faith Turner' },
      { value: 'joshuamacdonald@example.com', label: 'Joshua Mac Donald' },
      { value: 'unadavidson@example.com', label: 'Una Davidson' },
      { value: 'owenkerr@example.com', label: 'Owen Kerr' },
      { value: 'jantaylor@example.com', label: 'Jan Taylor' },
      { value: 'theresawalker@example.com', label: 'Theresa Walker' },
      { value: 'ryanterry@example.com', label: 'Ryan Terry' },
      { value: 'peneloperandall@example.com', label: 'Penelope Randall' },
      { value: 'donnaskinner@example.com', label: 'Donna Skinner' },
      { value: 'yvonneharris@example.com', label: 'Yvonne Harris' },
      { value: 'neilavery@example.com', label: 'Neil Avery' },
      { value: 'neilmanning@example.com', label: 'Neil Manning' },
      { value: 'maxblack@example.com', label: 'Max Black' },
      { value: 'deirdrerees@example.com', label: 'Deirdre Rees' },
      { value: 'justincampbell@example.com', label: 'Justin Campbell' },
      { value: 'donnahill@example.com', label: 'Donna Hill' },
    ],
  },
];
